run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - revive
    - gocritic
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - bodyclose

linters-settings:
  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
      - name: var-naming
      - name: error-return
      - name: error-naming
      - name: unexported-return
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
